services:
  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
      args:
        REGISTRY_PREFIX: ${REGISTRY_PREFIX:-harbor.pg.innopolis.university/docker-hub-cache/}
    restart: unless-stopped
    networks:
      - lms-network
    depends_on:
      backend:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - BOT_TOKEN=${BOT_TOKEN:?'BOT_TOKEN is required'}
      - LMS_API_KEY=${LMS_API_KEY:?'LMS_API_KEY is required'}
      - LMS_API_BASE_URL=http://backend:${BACKEND_CONTAINER_PORT:?'BACKEND_CONTAINER_PORT is required'}
      - LLM_API_KEY=${LLM_API_KEY:?'LLM_API_KEY is required'}
      - LLM_API_MODEL=${LLM_API_MODEL:?'LLM_API_MODEL is required'}
      - LLM_API_BASE_URL=http://host.docker.internal:42005/v1

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        REGISTRY_PREFIX: ${REGISTRY_PREFIX:-harbor.pg.innopolis.university/docker-hub-cache/}
    restart: unless-stopped
    networks:
      - lms-network
    ports:
      - ${BACKEND_HOST_ADDRESS:?'BACKEND_HOST_ADDRESS is required'}:${BACKEND_HOST_PORT:?'BACKEND_HOST_PORT is required'}:${BACKEND_CONTAINER_PORT}
    expose:
      - ${BACKEND_CONTAINER_PORT}
    environment:
      - NAME=${BACKEND_NAME:?'BACKEND_NAME is required'}
      - DEBUG=${BACKEND_DEBUG:?'BACKEND_DEBUG is required'}
      - ADDRESS=${BACKEND_CONTAINER_ADDRESS:?'BACKEND_CONTAINER_ADDRESS is required'}
      - PORT=${BACKEND_CONTAINER_PORT:?'BACKEND_CONTAINER_PORT is required'}
      - LMS_API_KEY=${LMS_API_KEY:?'LMS_API_KEY is required'}
      - BACKEND_ENABLE_INTERACTIONS=${BACKEND_ENABLE_INTERACTIONS:?'BACKEND_ENABLE_INTERACTIONS is required'}
      - BACKEND_ENABLE_LEARNERS=${BACKEND_ENABLE_LEARNERS:?'BACKEND_ENABLE_LEARNERS is required'}
      - AUTOCHECKER_API_URL=${AUTOCHECKER_API_URL:?'AUTOCHECKER_API_URL is required'}
      - AUTOCHECKER_API_LOGIN=${AUTOCHECKER_API_LOGIN:?'AUTOCHECKER_API_LOGIN is required'}
      - AUTOCHECKER_API_PASSWORD=${AUTOCHECKER_API_PASSWORD:?'AUTOCHECKER_API_PASSWORD is required'}
      - DB_HOST=${CONST_POSTGRESQL_SERVICE_NAME:?'CONST_POSTGRESQL_SERVICE_NAME is required'}
      - DB_PORT=${CONST_POSTGRESQL_DEFAULT_PORT:?'CONST_POSTGRESQL_DEFAULT_PORT is required'}
      - DB_NAME=${POSTGRES_DB:?'POSTGRES_DB is required'}
      - DB_USER=${POSTGRES_USER:?'POSTGRES_USER is required'}
      - DB_PASSWORD=${POSTGRES_PASSWORD:?'POSTGRES_PASSWORD is required'}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: ${REGISTRY_PREFIX:-harbor.pg.innopolis.university/docker-hub-cache/}postgres:18.3-alpine
    restart: unless-stopped
    networks:
      - lms-network
    environment:
      - POSTGRES_DB=${POSTGRES_DB:?'POSTGRES_DB is required'}
      - POSTGRES_USER=${POSTGRES_USER:?'POSTGRES_USER is required'}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?'POSTGRES_PASSWORD is required'}
    ports:
      - ${POSTGRES_HOST_ADDRESS:?'POSTGRES_HOST_ADDRESS is required'}:${POSTGRES_HOST_PORT:?'POSTGRES_HOST_PORT is required'}:${CONST_POSTGRESQL_DEFAULT_PORT:?'CONST_POSTGRESQL_DEFAULT_PORT is required'}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/app/data/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:?'POSTGRES_USER is required'} -d ${POSTGRES_DB:?'POSTGRES_DB is required'}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: ${REGISTRY_PREFIX:-harbor.pg.innopolis.university/docker-hub-cache/}dpage/pgadmin4:latest
    restart: unless-stopped
    networks:
      - lms-network
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:?'PGADMIN_EMAIL is required'}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:?'PGADMIN_PASSWORD is required'}
      - SCRIPT_NAME=/utils/pgadmin
    ports:
      - ${PGADMIN_HOST_ADDRESS:?'PGADMIN_HOST_ADDRESS is required'}:${PGADMIN_HOST_PORT:?'PGADMIN_HOST_PORT is required'}:80
    depends_on:
      postgres:
        condition: service_healthy

  caddy:
    build:
      context: frontend/
      args:
        REGISTRY_PREFIX: ${REGISTRY_PREFIX:-harbor.pg.innopolis.university/docker-hub-cache/}
    networks:
      - lms-network
    depends_on:
      - backend
      - bot
    environment:
      - CADDY_CONTAINER_PORT=${CADDY_CONTAINER_PORT:?'CADDY_CONTAINER_PORT is required'}
      - BACKEND_CONTAINER_PORT=${BACKEND_CONTAINER_PORT:?'BACKEND_CONTAINER_PORT is required'}
      - QWEN_CODE_API_URL=${QWEN_CODE_API_URL:?'QWEN_CODE_API_URL is required'}
    ports:
      - ${LMS_API_HOST_ADDRESS:?'LMS_API_HOST_ADDRESS is required'}:${LMS_API_HOST_PORT:?'LMS_API_HOST_PORT is required'}:${CADDY_CONTAINER_PORT}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile

volumes:
  postgres_data:

networks:
  lms-network:
    name: lms-network
    attachable: true
